/*
 * loanpymntintfr.java
 *
 * Created on August 13, 2002, 1:09 PM
 */

package com.afrisoftech.sacco;

/**
 *
 * @author  root
 */
public class MemResignationintfr extends javax.swing.JInternalFrame {
    
    /** Creates new form loanpymntintfr */
      
       java.sql.Connection connectDB = null;
    
    org.netbeans.lib.sql.pool.PooledConnectionSource pConnDB = null;
      javax.swing.JSpinner beginDateSpinner = null;
    
      
      javax.swing.JSpinner endDateSpinner = null;

    
      public MemResignationintfr(java.sql.Connection connDb, org.netbeans.lib.sql.pool.PooledConnectionSource pconnDB) {
        
        connectDB = connDb;
        
        pConnDB = pconnDB;
        
        initComponents();
    }   
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        pconn1 = new org.netbeans.lib.sql.pool.PooledConnectionSource();
        try {
            crset1 = new org.netbeans.lib.sql.NBCachedRowSet();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        try {
            crset4 = new org.netbeans.lib.sql.NBCachedRowSet();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        buttonGroup1 = new javax.swing.ButtonGroup();
        try {
            crset2 = new org.netbeans.lib.sql.NBCachedRowSet();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        try {
            crset5 = new org.netbeans.lib.sql.NBCachedRowSet();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();

        pconn1.setDatabase("jdbc:postgresql://localhost:5432/sako");
        pconn1.setDriver("org.postgresql.Driver");
        pconn1.setUsername("postgres");
        crset1.setCommand("select m_number from member where status != 'Resigned' order by m_number");
        crset1.setConnectionSource(pConnDB);
        crset4.setConnectionSource(pConnDB);
        crset2.setCommand("select bank_acc_no from bank_branches");
        crset2.setConnectionSource(pConnDB);
        crset5.setConnectionSource(pConnDB);

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Member Resignation");
        setToolTipText("Caution!! Make sure you have entered all the necessary information before ticking");
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ColorPreview.gif")));
        setVisible(true);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.gif")));
        jButton1.setMnemonic('O');
        jButton1.setText("Ok");
        jButton1.setToolTipText("Click here to enter data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jButton1, gridBagConstraints);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/note[1].gif")));
        jButton2.setMnemonic('E');
        jButton2.setText("Edit");
        jButton2.setToolTipText("Click here to edit data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jButton2, gridBagConstraints);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minusarm.gif")));
        jButton3.setMnemonic('n');
        jButton3.setText("Cancel");
        jButton3.setToolTipText("Click here to clear text fields");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jButton3, gridBagConstraints);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BD14753_.GIF")));
        jButton4.setMnemonic('C');
        jButton4.setText("Close");
        jButton4.setToolTipText("Click here to close window");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jButton4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jSeparator1, gridBagConstraints);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jLabel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jLabel3, gridBagConstraints);

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Cursor", 0, 12));
        jTextField8.setForeground((java.awt.Color) javax.swing.UIManager.getDefaults().get("InternalFrame.borderColor"));
        jTextField8.setBorder(null);
        jTextField8.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        getContentPane().add(jTextField8, gridBagConstraints);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Cursor", 0, 12));
        jTextField10.setForeground((java.awt.Color) javax.swing.UIManager.getDefaults().get("InternalFrame.borderColor"));
        jTextField10.setBorder(null);
        jTextField10.setPreferredSize(new java.awt.Dimension(0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        getContentPane().add(jTextField10, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder("Select Member account here"));
        jLabel1.setText("Member Code");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jLabel1, gridBagConstraints);

        jComboBox1.setModel(new org.netbeans.lib.sql.models.ComboBoxModel (crset1, "lpad", null, null, null));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel1.add(jComboBox1, gridBagConstraints);

        jLabel2.setText("Member Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jLabel2, gridBagConstraints);

        jTextField11.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel1.add(jTextField11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Enter payee detail's here"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loan Acc. No.", "Loan Type", "Balance", "Amt Paid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        jPanel4.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 7.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(new javax.swing.border.TitledBorder(null, "Member Earnings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0)));
        jLabel10.setText("Payable Amt KShs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(jLabel10, gridBagConstraints);

        jTextField6.setEditable(false);
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel5.add(jTextField6, gridBagConstraints);

        jLabel14.setText("Loan Balance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel5.add(jLabel14, gridBagConstraints);

        jTextField15.setEditable(false);
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel5.add(jTextField15, gridBagConstraints);

        jLabel6.setText("Total Shares");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(jLabel6, gridBagConstraints);

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPanel5.add(jTextField4, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Share Type", "Amount"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 9.0;
        jPanel3.add(jScrollPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 5.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        getContentPane().add(jPanel5, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jPanel6.setBorder(new javax.swing.border.TitledBorder(null, "Reason for resigning", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel6.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 4.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(jPanel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabel4, gridBagConstraints);

        setBounds(0, 0, 700, 500);
    }//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     this.setVisible(false);           // Add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      //jTextField1.setText("");
//      jTextField2.setText(""); 
//      jTextField3.setText(""); 
      jTextField4.setText("");
      jTextField11.setText(""); 
//      jTextField5.setText("");
//      jTextField9.setText("");
     // jTextField12.setText(""); 
//      jTextField13.setText("");
//      jTextField14.setText("");
      jTextField6.setText(""); 
      jTextField15.setText("");
    //  jTextField7.setText("");
      jComboBox1.setSelectedItem("");
//      jComboBox12.setSelectedItem("");
      // Add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       javax.swing.JFrame lpay = new SharesRefund(connectDB,pConnDB);
     lpay.setVisible(true);  // Add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
         
        java.util.Calendar calendar = java.util.Calendar.getInstance();
        
        long dateNow = calendar.getTimeInMillis();
        
        java.sql.Date datenowSql= new java.sql.Date(dateNow);
        
        System.out.println(datenowSql.toString());
 
     
        
        try {
            connectDB.setAutoCommit(false);
            java.sql.Statement stmts = connectDB.createStatement();
            java.sql.ResultSet rsets = stmts.executeQuery("select code from activity where activity ='Shares Refund'");
            while (rsets.next())
             rsets.getObject(1).toString();
           
            String shaRefCode = rsets.getObject(1).toString();
       
           
            java.sql.Statement ps = connectDB.createStatement();            
            java.sql.ResultSet rst = ps.executeQuery("select nextval('transaction_no_seq')");
            while (rst.next())
            rst.getObject(1).toString();
             ps.close();
             rst.close();
             
             String transNo = rst.getObject(1).toString();
       
            
           
      java.sql.PreparedStatement pstmt = connectDB.prepareStatement("insert into shares_transactions values(?,?,?,?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?,?,?,?,?,?)");
         for (int k = 0; k < jTable2.getRowCount(); k++){
           pstmt.setString(1,jComboBox1.getSelectedItem().toString());
            pstmt.setString(2,jTextField11.getText());
            pstmt.setString(3,"");
            pstmt.setString(4,"");
            pstmt.setString(5,"");
            pstmt.setString(6,"");
            pstmt.setString(7,"");
            pstmt.setString(8,"");
            pstmt.setString(9,"");
            pstmt.setString(10,jTable2.getValueAt(k,0).toString());
            pstmt.setString(11,jTable2.getValueAt(k,2).toString());
            pstmt.setString(12,"00");
            pstmt.setString(13,"");
            pstmt.setString(14,jTable2.getValueAt(k,1).toString());
            pstmt.setDate(15, datenowSql);
            pstmt.setString(16,""+transNo+"");            
            pstmt.setBoolean(17,false);
            pstmt.setString(18,"");
            pstmt.setString(19,"");
            pstmt.setString(20,"Shares Refund");
            pstmt.executeUpdate();
         }
            float bal = java.lang.Float.parseFloat(jTextField6.getText());
        
             java.sql.PreparedStatement pstmts = connectDB.prepareStatement("insert into member_resignation values(?,?,?,?,?)");
            pstmts.setString(1,jComboBox1.getSelectedItem().toString());
            pstmts.setString(2,jTextField11.getText());
            if(bal > 0){
            pstmts.setString(3,jTextField6.getText());
            }else{
               pstmts.setString(3,"00");
            }
             pstmts.setString(4,"00");
            
            pstmts.setString(5,jTextPane1.getText());
           pstmts.executeUpdate();
            
            if(bal > 0){
            java.sql.PreparedStatement pstmt1 = connectDB.prepareStatement("insert into shares_transactions values(?,?,?,?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?,?,?,?,?,?)");
            pstmt1.setString(1,jComboBox1.getSelectedItem().toString());
            pstmt1.setString(2,jTextField11.getText());
            pstmt1.setString(3,"");
            pstmt1.setString(4,"");
            pstmt1.setString(5,"");
            pstmt1.setString(6,"");
            pstmt1.setString(7,"");
            pstmt1.setString(8,"");
            pstmt1.setString(9,"");
            pstmt1.setString(10,"Shares Refund");
            pstmt1.setString(11,"00");
            pstmt1.setString(12,jTextField6.getText());
            pstmt1.setString(13,"");
            pstmt1.setString(14,""+shaRefCode+"");
            pstmt1.setDate(15, datenowSql);
            pstmt1.setString(16,""+transNo+"");            
            pstmt1.setBoolean(17,false);
            pstmt1.setString(18,"");
            pstmt1.setString(19,"");
            pstmt1.setString(20,"Shares Refund");
         
            pstmt1.executeUpdate();
            }
       
            
        for (int i = 0; i < jTable1.getRowCount(); i++){
        if (jTable1.getModel().getValueAt(i,5) != null){
             java.sql.Statement stmt = connectDB.createStatement();
            java.sql.ResultSet rset = stmt.executeQuery("select code from activity where activity ='Interest From Loans'");
            while (rset.next())
             rset.getObject(1).toString();
            rset.close();
            String intrestCode = rset.getObject(1).toString();
            
            java.sql.Statement st = connectDB.createStatement();
            java.sql.ResultSet rs = st.executeQuery("select code from activity where activity ='"+jTable1.getValueAt(i,1).toString()+"'");
            while (rs.next())
             rs.getObject(1).toString();
           // rs.close();
            String loanCode = rs.getObject(1).toString();
             float intr = java.lang.Float.parseFloat(jTable1.getModel().getValueAt(i,2).toString());
             float prin = java.lang.Float.parseFloat(jTable1.getValueAt(i,3).toString());
             float amt = java.lang.Float.parseFloat(jTable1.getValueAt(i,5).toString());
             float balance = java.lang.Float.parseFloat(jTable1.getValueAt(i,4).toString());
       
             float bal1 = amt - intr;
    
         java.sql.PreparedStatement pst2 = connectDB.prepareStatement("insert into loan_transactions values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst2.setString(1,jTable1.getValueAt(i,0).toString());
            pst2.setString(2,jTextField11.getText());
            pst2.setString(3,jComboBox1.getSelectedItem().toString());
            pst2.setString(4,"Interest From Loans");
            pst2.setString(5,"");
            pst2.setString(6,"");
            pst2.setString(7,"");
            pst2.setString(8,"");
            pst2.setString(9,"");
            pst2.setString(10,"");
            pst2.setString(11,"");
            pst2.setString(12,"00");
            pst2.setString(13,"00");
            pst2.setString(14,"00");
            pst2.setString(15,"00");
           if(amt >= intr){
        
          pst2.setString(16,jTable1.getModel().getValueAt(i,2).toString());
          
          } else{
           pst2.setString(16,jTable1.getValueAt(i,5).toString());
        
            }
          //  pst2.setString(16,jTextField10.getText());
            pst2.setString(17,"00");
            if(amt >= intr){
        
          pst2.setString(18,jTable1.getModel().getValueAt(i,2).toString());
          
          } else{
           pst2.setString(18,jTable1.getValueAt(i,5).toString());
        
            }
           // pst2.setString(18,"00");
            pst2.setString(19,"");
            pst2.setString(20,"Loan Clearance");
            pst2.setString(21,"");
            pst2.setString(22,""+intrestCode+"");
            pst2.setDate(23, datenowSql);
            pst2.setString(24,""+transNo+"");            
            pst2.setBoolean(25,false);
            pst2.setString(26,"");
         
            pst2.executeUpdate();
            
            java.sql.PreparedStatement pstmt2 = connectDB.prepareStatement("insert into loan_transactions values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pstmt2.setString(1,jTable1.getValueAt(i,0).toString());
            pstmt2.setString(2,jTextField11.getText());
            pstmt2.setString(3,jComboBox1.getSelectedItem().toString());
            pstmt2.setString(4,jTable1.getValueAt(i,1).toString());
            pstmt2.setString(5,"");
            pstmt2.setString(6,"");
            pstmt2.setString(7,"");
            pstmt2.setString(8,"");
            pstmt2.setString(9,"");
            pstmt2.setString(10,"");
            pstmt2.setString(11,"");
            pstmt2.setString(12,"00");
            pstmt2.setString(13,"00");
            pstmt2.setString(14,"00");
            pstmt2.setString(15,""+bal1+"");
            pstmt2.setString(16,"00");
            pstmt2.setString(17,"00");
            pstmt2.setString(18,""+bal1+"");
            pstmt2.setString(19,"");
            pstmt2.setString(20,"Loan Clearance");
            pstmt2.setString(21,"");
            pstmt2.setString(22,""+loanCode+"");
            pstmt2.setDate(23, datenowSql);
            pstmt2.setString(24,""+transNo+"");            
            pstmt2.setBoolean(25,false);
            pstmt2.setString(26,"");
            pstmt2.executeUpdate();
               
                if (amt == balance) {
             java.sql.PreparedStatement pstt = connectDB.prepareStatement ("DELETE from guarantors where lacc = '"+jTable1.getValueAt(i,0).toString()+"'");
          
             pstt.executeUpdate();
             java.sql.PreparedStatement pstt1 = connectDB.prepareStatement ("update approved_loans set cleared = 'true' where loan_acc_no = '"+jTable1.getValueAt(i,0).toString()+"'");
          
             pstt1.executeUpdate();
             
             }
            
           }
           
        }
            java.sql.PreparedStatement pst = connectDB.prepareStatement ("update member set status = 'Resigned' where m_number = '"+jComboBox1.getSelectedItem().toString()+"'");
          
             pst.executeUpdate();
    
             connectDB.commit();
             connectDB.setAutoCommit(true);
             jButton1.setEnabled(false);
              jLabel4.setForeground(java.awt.Color.blue);
            jLabel4.setText("Insert Successful");
                 }   catch(java.sql.SQLException sq){
                   System.out.println(sq.getMessage());
                   javax.swing.JOptionPane.showMessageDialog(this,sq.getMessage(),"Error Message!",javax.swing.JOptionPane.ERROR_MESSAGE);
                    try {
                  connectDB.rollback();
                    }catch (java.sql.SQLException sql){
                    javax.swing.JOptionPane.showMessageDialog(this,sql.getMessage(),"Error Message!",javax.swing.JOptionPane.ERROR_MESSAGE);
                }
              }
       // Add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
             jButton1.setEnabled(true);
        this.jTextField8.setVisible(false);
              jTextField10.setVisible(false);
              int j = 0;
       
        try {
            java.sql.Statement stmt = connectDB.createStatement();
            java.sql.ResultSet rset = stmt.executeQuery("select suffix ||' '||first_name||' '||middle_name||' '||last_name from member where m_number ='"+jComboBox1.getSelectedItem()+"'");
            while (rset.next())
            jTextField11.setText(rset.getObject(1).toString());
            } catch (java.sql.SQLException sqe) {
           sqe.printStackTrace();
            System.out.println("Insert not successful");
        }  
       
            try {
       
        
         crset5.setCommand("select share_type,activity_code,sum(-debit + credit) as amount from shares_transactions where member_code ='"+jComboBox1.getSelectedItem().toString()+"' AND share_type != 'Entrance Fee' AND share_type != 'Dividend Payable' AND share_type != 'Interest Payable' AND share_type !='Shares Refund' group by share_type,member_code,activity_code");
         crset5.setConnectionSource(pConnDB);
 
         crset5.execute();
        
         jTable2.setModel(new org.netbeans.lib.sql.models.TableModel(crset5, new org.netbeans.lib.sql.models.TableModel.Column[] {
          
            new org.netbeans.lib.sql.models.TableModel.Column("share_type", "Shares Type", false),
            new org.netbeans.lib.sql.models.TableModel.Column("activity_code", "Loan Type", false),
            new org.netbeans.lib.sql.models.TableModel.Column("amount", "Value KShs.", false),
           }));
    
        jScrollPane3.setViewportView(jTable2);
      
       } catch(java.sql.SQLException sqlex){
          javax.swing.JOptionPane.showMessageDialog(this,sqlex.getMessage(),"Error Message!",javax.swing.JOptionPane.ERROR_MESSAGE);
 
        System.out.println(sqlex.getMessage());
                
        }              
              
             try {
       
        
         crset4.setCommand("select loan_account_no,loan_type,interest,principal,balance,null as amount from loan_clearance_view where member_no ='"+jComboBox1.getSelectedItem().toString()+"'");
         crset4.setConnectionSource(pConnDB);
 
         crset4.execute();
        
         jTable1.setModel(new org.netbeans.lib.sql.models.TableModel(crset4, new org.netbeans.lib.sql.models.TableModel.Column[] {
            new org.netbeans.lib.sql.models.TableModel.Column("loan_account_no", "Loan Acc. No. ", false),
           // new org.netbeans.lib.sql.models.TableModel.Column("activity_code", "Code", false),
            new org.netbeans.lib.sql.models.TableModel.Column("loan_type", "Loan Type", false),
            new org.netbeans.lib.sql.models.TableModel.Column("interest", "Interest", true),
            new org.netbeans.lib.sql.models.TableModel.Column("principal", "Princ.Bal.", true),
            new org.netbeans.lib.sql.models.TableModel.Column("balance", "Balance", false),
            new org.netbeans.lib.sql.models.TableModel.Column("amount", "Amount", true)
           
            }));
    
        jScrollPane2.setViewportView(jTable1);
      
       } catch(java.sql.SQLException sqlex){
          javax.swing.JOptionPane.showMessageDialog(this,sqlex.getMessage(),"Error Message!",javax.swing.JOptionPane.ERROR_MESSAGE);
 
        System.out.println(sqlex.getMessage());
                
        }    
              
              
               float num_a = 0;
               float num_b = 0;
               float num_c = 0;
               float num_d = 0;
              
               jTextField15.setText("00");
               
               float SHARES = 0;
     try {
            java.sql.Statement stmt5 = connectDB.createStatement();
          
        java.sql.ResultSet rset5 = stmt5.executeQuery("select sum(-debit + credit) as amount from shares_transactions where member_code ='"+jComboBox1.getSelectedItem().toString()+"' AND share_type != 'Entrance Fee' AND share_type != 'Dividend Payable' AND share_type != 'Interest Payable'");
        while (rset5.next())
          jTextField4.setText(rset5.getString(1));
            SHARES = rset5.getFloat(1);
        } catch (java.sql.SQLException sqe) {
           sqe.printStackTrace();
            System.out.println("Insert not successful");
        } 
          
               try {
            java.sql.Statement stmt = connectDB.createStatement();
            java.sql.Statement stmt1 = connectDB.createStatement();
            java.sql.ResultSet rset = stmt.executeQuery("select round(sum(principal + interest)-sum(principal_paid + interest_paid),2) from loan_transactions where member_no ='"+jComboBox1.getSelectedItem()+"'");
             java.sql.ResultSet rset1 = stmt1.executeQuery("select count(member_no) from loan_transactions where member_no ='"+jComboBox1.getSelectedItem()+"'");
            while (rset1.next()) {
                j = rset1.getInt(1);
            }
             if (j > 0){
            while (rset.next())
            jTextField15.setText(rset.getString(1));
           } else 
               jTextField15.equals("00");
            } catch (java.sql.SQLException sqe) {
           sqe.printStackTrace();
            System.out.println("Insert not successful");
        }  
     
           num_d = java.lang.Float.parseFloat(jTextField15.getText());
 
           float total_num =  SHARES - num_d;
           System.out.println(total_num);
                
         
            this.jTextField6.setText(""+total_num+"");
 
            // Add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField6;
    private org.netbeans.lib.sql.NBCachedRowSet crset5;
    private javax.swing.JButton jButton2;
    private javax.swing.JTable jTable2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private org.netbeans.lib.sql.NBCachedRowSet crset2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel jPanel2;
    private org.netbeans.lib.sql.NBCachedRowSet crset4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jPanel1;
    private org.netbeans.lib.sql.NBCachedRowSet crset1;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane3;
    private org.netbeans.lib.sql.pool.PooledConnectionSource pconn1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
