/*
 * Generated by JDBC Form Wizard
 *
 * PropertyPurchase.java
 *
 * Created on Jun 10, 2003, 07:58 AM
*/

package com.afrisoftech.sacco;

/**
 *
 * @author  root
 * @version 
 */

public class PropertyPurchase extends javax.swing.JFrame
{

    java.sql.Connection connectDB = null;
    
    org.netbeans.lib.sql.pool.PooledConnectionSource pConnDB = null;
  
    
    public PropertyPurchase(java.sql.Connection connDb, org.netbeans.lib.sql.pool.PooledConnectionSource pconnDB) {
        
        connectDB = connDb;
        
        pConnDB = pconnDB;
        
        initComponents();
    }   

    private void initComponents() {//GEN-BEGIN:initComponents
        try {
            nBCachedRowSet1 = new org.netbeans.lib.sql.NBCachedRowSet();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        dataNavigator1 = new org.netbeans.lib.sql.DataNavigator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        nBCachedRowSet1.setCommand("select * from property_purchase");
        nBCachedRowSet1.setConnectionSource(pConnDB);
        try {
            nBCachedRowSet1.setTableName("property_purchase");
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }

        setTitle("Property Purchase");
        try {
            dataNavigator1.setLayoutButtons(1);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        dataNavigator1.setRowSet(nBCachedRowSet1);
        getContentPane().add(dataNavigator1, java.awt.BorderLayout.SOUTH);

        jTable1.setModel(new org.netbeans.lib.sql.models.TableModel(nBCachedRowSet1, new org.netbeans.lib.sql.models.TableModel.Column[] {
            new org.netbeans.lib.sql.models.TableModel.Column("property_type", "Property type", true),
            new org.netbeans.lib.sql.models.TableModel.Column("property_value", "Property value", true),
            new org.netbeans.lib.sql.models.TableModel.Column("registration_no", "Registration no", true),
            new org.netbeans.lib.sql.models.TableModel.Column("serial_no", "Serial no", true),
            new org.netbeans.lib.sql.models.TableModel.Column("date_of_purchase", "Date of purchase", true),
            new org.netbeans.lib.sql.models.TableModel.Column("plot_no", "Plot no", true),
            new org.netbeans.lib.sql.models.TableModel.Column("size", "Size", true),
            new org.netbeans.lib.sql.models.TableModel.Column("year_of_manufacture", "Year of manufacture", true),
            new org.netbeans.lib.sql.models.TableModel.Column("town", "Town", true),
            new org.netbeans.lib.sql.models.TableModel.Column("estate", "Estate", true),
            new org.netbeans.lib.sql.models.TableModel.Column("date", "Date", true)
        }));
        jTable1.setSelectionModel(new org.netbeans.lib.sql.models.SQLListSelectionModel (nBCachedRowSet1));
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("Master view", null, jScrollPane1, "");

        jTable2.setModel(new org.netbeans.lib.sql.models.TableModel(nBCachedRowSet1, new org.netbeans.lib.sql.models.TableModel.Column[] {
            new org.netbeans.lib.sql.models.TableModel.Column("property_type", "Property type", false),
            new org.netbeans.lib.sql.models.TableModel.Column("property_value", "Property value", false),
            new org.netbeans.lib.sql.models.TableModel.Column("registration_no", "Registration no", false),
            new org.netbeans.lib.sql.models.TableModel.Column("serial_no", "Serial no", false),
            new org.netbeans.lib.sql.models.TableModel.Column("date_of_purchase", "Date of purchase", false),
            new org.netbeans.lib.sql.models.TableModel.Column("plot_no", "Plot no", false),
            new org.netbeans.lib.sql.models.TableModel.Column("size", "Size", false),
            new org.netbeans.lib.sql.models.TableModel.Column("year_of_manufacture", "Year of manufacture", false),
            new org.netbeans.lib.sql.models.TableModel.Column("town", "Town", false),
            new org.netbeans.lib.sql.models.TableModel.Column("estate", "Estate", false),
            new org.netbeans.lib.sql.models.TableModel.Column("voucher_no", "Voucher no", false),
            new org.netbeans.lib.sql.models.TableModel.Column("name", "Name", false),
            new org.netbeans.lib.sql.models.TableModel.Column("amount", "Amount", false),
            new org.netbeans.lib.sql.models.TableModel.Column("seller", "Seller", false),
            new org.netbeans.lib.sql.models.TableModel.Column("id_no", "Id no", false),
            new org.netbeans.lib.sql.models.TableModel.Column("pin_no", "Pin no", false),
            new org.netbeans.lib.sql.models.TableModel.Column("address", "Address", false),
            new org.netbeans.lib.sql.models.TableModel.Column("telephone_no", "Telephone no", false),
            new org.netbeans.lib.sql.models.TableModel.Column("premises", "Premises", false),
            new org.netbeans.lib.sql.models.TableModel.Column("date", "Date", false)
        }));
        jTable2.setSelectionModel(new org.netbeans.lib.sql.models.SQLListSelectionModel (nBCachedRowSet1));
        jScrollPane2.setViewportView(jTable2);

        jTabbedPane1.addTab("Detail view", null, jScrollPane2, "");

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 900, 300);
    }//GEN-END:initComponents

    public static void main(String[] args)
    {
      //  new PropertyPurchase().show();    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.netbeans.lib.sql.NBCachedRowSet nBCachedRowSet1;
    private org.netbeans.lib.sql.DataNavigator dataNavigator1;
    // End of variables declaration//GEN-END:variables

}

