/*
 * RecruitmentRequestsIntfr.java
 *
 * Created on February 1, 2005, 3:37 PM
 */

package com.afrisoftech.hr;

/**
 *
 * @author  root
 */
public class RecruitmentRequestsIntfr extends javax.swing.JInternalFrame {
    
    java.sql.Connection connectDB1 = null;
    
    javax.swing.table.TableModel tableModel = null;
    
    javax.swing.JSpinner beginDateSpinner = null;
    
    javax.swing.JSpinner endDateSpinner = null;
    
    org.netbeans.lib.sql.pool.PooledConnectionSource pConnDB = null;
    /** Creates new form DefaultInternalFrame */
    public RecruitmentRequestsIntfr(java.sql.Connection connDb, org.netbeans.lib.sql.pool.PooledConnectionSource pconnDB) {
        
        connectDB1 = connDb;
        
        pConnDB = pconnDB;
        
        initComponents();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        try {
            nBCachedRowSet1 = new org.netbeans.lib.sql.NBCachedRowSet();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        try {
            nBCachedRowSet2 = new org.netbeans.lib.sql.NBCachedRowSet();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        try {
            nBCachedRowSet3 = new org.netbeans.lib.sql.NBCachedRowSet();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        try {
            nBCachedRowSet4 = new org.netbeans.lib.sql.NBCachedRowSet();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        try {
            nBCachedRowSet5 = new org.netbeans.lib.sql.NBCachedRowSet();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        mainpanel = new javax.swing.JPanel();
        datapanel02 = new javax.swing.JPanel();
        insertbtm = new javax.swing.JButton();
        selectbtm = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        editpanel2 = new javax.swing.JPanel();
        newbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        spacerPanel = new javax.swing.JPanel();
        helppanel2 = new javax.swing.JPanel();
        helpbtn = new javax.swing.JButton();
        subMainPanel311 = new javax.swing.JPanel();
        jPanel1211 = new javax.swing.JPanel();
        jLabel3111 = new javax.swing.JLabel();
        jLabel4111 = new javax.swing.JLabel();
        jLabel6111 = new javax.swing.JLabel();
        jLabel7111 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox21 = new javax.swing.JComboBox();
        jLabel31112 = new javax.swing.JLabel();
        jLabel311111 = new javax.swing.JLabel();
        datePicker1 = new com.afrisoftech.lib.DatePicker();
        datePicker111 = new com.afrisoftech.lib.DatePicker();
        jLabel61111 = new javax.swing.JLabel();
        jComboBox111 = new javax.swing.JComboBox();
        jLabel611111 = new javax.swing.JLabel();
        jComboBox2111 = new javax.swing.JComboBox();
        jTextField411121 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        fieldsPanel3111 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane31 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        nBCachedRowSet1.setCommand("select DISTINCT department_name as name FROM hr.hr_department ORDER BY name");
        nBCachedRowSet1.setConnectionSource(pConnDB);
        nBCachedRowSet2.setCommand("SELECT DISTINCT UPPER(management_level_designation) as name FROM hr.hr_management_hierachies UNION ALL SELECT UPPER(designation) FROM hr.hr_job_designation order by name");
        nBCachedRowSet2.setConnectionSource(pConnDB);
        nBCachedRowSet3.setCommand("select DISTINCT UPPER(req_type)  as type FROM hr.hr_req_type ORDER BY type");
        nBCachedRowSet3.setConnectionSource(pConnDB);
        nBCachedRowSet4.setCommand("select DISTINCT UPPER(category_desc)  as job FROM hr.hr_job_category ORDER BY job");
        nBCachedRowSet4.setConnectionSource(pConnDB);
        nBCachedRowSet5.setCommand("select DISTINCT UPPER(autho_desc)  as authority FROM hr.hr_authority ORDER BY authority");
        nBCachedRowSet5.setConnectionSource(pConnDB);

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("JOB REQUISITION INFORMATION");
        setVisible(true);
        mainpanel.setLayout(new java.awt.GridBagLayout());

        mainpanel.setBorder(new javax.swing.border.TitledBorder(""));
        datapanel02.setLayout(new java.awt.GridBagLayout());

        datapanel02.setBorder(new javax.swing.border.EtchedBorder());
        insertbtm.setText("Insert");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        datapanel02.add(insertbtm, gridBagConstraints);

        selectbtm.setText("Select");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        datapanel02.add(selectbtm, gridBagConstraints);

        deletebtn.setText("Delete");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        datapanel02.add(deletebtn, gridBagConstraints);

        updatebtn.setText("Update");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        datapanel02.add(updatebtn, gridBagConstraints);

        closebtn.setText("Close");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        datapanel02.add(closebtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.weightx = 10.0;
        mainpanel.add(datapanel02, gridBagConstraints);

        editpanel2.setLayout(new java.awt.GridBagLayout());

        editpanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        newbtn.setText("New");
        newbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbtnActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        editpanel2.add(newbtn, gridBagConstraints);

        cancelbtn.setText("Update");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        editpanel2.add(cancelbtn, gridBagConstraints);

        editbtn.setText("Delete");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        editpanel2.add(editbtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 5.0;
        editpanel2.add(spacerPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        mainpanel.add(editpanel2, gridBagConstraints);

        helppanel2.setLayout(new java.awt.GridBagLayout());

        helppanel2.setBorder(new javax.swing.border.TitledBorder("Assistance"));
        helpbtn.setText("Help");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        helppanel2.add(helpbtn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        mainpanel.add(helppanel2, gridBagConstraints);

        subMainPanel311.setLayout(new java.awt.GridBagLayout());

        subMainPanel311.setBorder(new javax.swing.border.TitledBorder(""));
        jPanel1211.setLayout(new java.awt.GridBagLayout());

        jPanel1211.setBorder(new javax.swing.border.TitledBorder("Enter the Required Info"));
        jLabel3111.setText("Requisition No.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        jPanel1211.add(jLabel3111, gridBagConstraints);

        jLabel4111.setText("Requisition Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        jPanel1211.add(jLabel4111, gridBagConstraints);

        jLabel6111.setText("Department ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        jPanel1211.add(jLabel6111, gridBagConstraints);

        jLabel7111.setText("Position/Title");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        jPanel1211.add(jLabel7111, gridBagConstraints);

        jComboBox1.setModel(new org.netbeans.lib.sql.models.ComboBoxModel (nBCachedRowSet4, "job", null, null, null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1211.add(jComboBox1, gridBagConstraints);

        jComboBox21.setModel(new org.netbeans.lib.sql.models.ComboBoxModel (nBCachedRowSet1, "name", null, null, null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1211.add(jComboBox21, gridBagConstraints);

        jLabel31112.setText("Job Category");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        jPanel1211.add(jLabel31112, gridBagConstraints);

        jLabel311111.setText("Date Due");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        jPanel1211.add(jLabel311111, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1211.add(datePicker1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1211.add(datePicker111, gridBagConstraints);

        jLabel61111.setText("Hiring Authority");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        jPanel1211.add(jLabel61111, gridBagConstraints);

        jComboBox111.setModel(new org.netbeans.lib.sql.models.ComboBoxModel (nBCachedRowSet5, "authority", null, null, null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1211.add(jComboBox111, gridBagConstraints);

        jLabel611111.setText("Requisition Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        jPanel1211.add(jLabel611111, gridBagConstraints);

        jComboBox2111.setModel(new org.netbeans.lib.sql.models.ComboBoxModel (nBCachedRowSet3, "type", null, null, null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1211.add(jComboBox2111, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1211.add(jTextField411121, gridBagConstraints);

        jComboBox2.setModel(new org.netbeans.lib.sql.models.ComboBoxModel (nBCachedRowSet2, "name", null, null, null));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 50.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1211.add(jComboBox2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        subMainPanel311.add(jPanel1211, gridBagConstraints);

        fieldsPanel3111.setLayout(new java.awt.GridBagLayout());

        fieldsPanel3111.setBorder(new javax.swing.border.TitledBorder("Requirements"));
        jScrollPane3.setViewportBorder(new javax.swing.border.TitledBorder(null, "Skills/Experience", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12)));
        jScrollPane3.setViewportView(jTextPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 100.0;
        fieldsPanel3111.add(jScrollPane3, gridBagConstraints);

        jScrollPane31.setViewportBorder(new javax.swing.border.TitledBorder(null, "Education", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12)));
        jScrollPane31.setViewportView(jTextPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 100.0;
        fieldsPanel3111.add(jScrollPane31, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.weightx = 10.0;
        gridBagConstraints.weighty = 50.0;
        subMainPanel311.add(fieldsPanel3111, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 20.0;
        gridBagConstraints.weighty = 20.0;
        mainpanel.add(subMainPanel311, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(mainpanel, gridBagConstraints);

        setBounds(0, 0, 663, 500);
    }//GEN-END:initComponents
    
    private void newbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbtnActionPerformed
        
        System.out.println("Connection Object ["+connectDB1+"]");
        try {
            
            connectDB1.setAutoCommit(false);
            java.sql.PreparedStatement pstmt = connectDB1.prepareStatement("insert into hr.hr_rec_request (rec_no,rec_type,department,advert_date,response_date,job_category,position,hiring_authority,education,skills) values(?,?,?,?,?,?,?,?,?,?)");
            
            pstmt.setObject(1,jTextField411121.getText());
            pstmt.setObject(2,jComboBox2111.getSelectedItem().toString());
            pstmt.setObject(3,jComboBox21.getSelectedItem().toString());
            pstmt.setObject(4,datePicker1.getDate());
            pstmt.setObject(5,datePicker111.getDate());
            pstmt.setObject(6,jComboBox1.getSelectedItem().toString());
            pstmt.setObject(7,jComboBox2.getSelectedItem().toString());
            pstmt.setObject(8,jComboBox111.getSelectedItem().toString());
            pstmt.setObject(9,jTextPane1.getText());
            pstmt.setObject(10,jTextPane1.getText());
            pstmt.executeUpdate();
            connectDB1.commit();
            connectDB1.setAutoCommit(true);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Data saved successfully","Confirmation Message",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            
            
        }   catch(java.sql.SQLException sq){
            javax.swing.JOptionPane.showMessageDialog(this, sq.getMessage(),"Error Message!",javax.swing.JOptionPane.ERROR_MESSAGE);
            try {
                connectDB1.rollback();
            }catch (java.sql.SQLException sql){
                javax.swing.JOptionPane.showMessageDialog(this,sql.getMessage(),"Error Message!",javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
        }
        // Add your handling code here:
    }//GEN-LAST:event_newbtnActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField411121;
    private javax.swing.JComboBox jComboBox21;
    private javax.swing.JButton selectbtm;
    private javax.swing.JTextPane jTextPane1;
    private org.netbeans.lib.sql.NBCachedRowSet nBCachedRowSet2;
    private javax.swing.JPanel mainpanel;
    private org.netbeans.lib.sql.NBCachedRowSet nBCachedRowSet5;
    private javax.swing.JLabel jLabel6111;
    private javax.swing.JPanel spacerPanel;
    private javax.swing.JButton insertbtm;
    private javax.swing.JPanel subMainPanel311;
    private javax.swing.JLabel jLabel611111;
    private javax.swing.JLabel jLabel31112;
    private javax.swing.JPanel datapanel02;
    private org.netbeans.lib.sql.NBCachedRowSet nBCachedRowSet4;
    private javax.swing.JComboBox jComboBox111;
    private javax.swing.JButton helpbtn;
    private javax.swing.JButton newbtn;
    private javax.swing.JPanel editpanel2;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JPanel fieldsPanel3111;
    private org.netbeans.lib.sql.NBCachedRowSet nBCachedRowSet3;
    private javax.swing.JComboBox jComboBox2111;
    private javax.swing.JLabel jLabel311111;
    private javax.swing.JButton updatebtn;
    private javax.swing.JPanel jPanel1211;
    private javax.swing.JButton editbtn;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JButton cancelbtn;
    private org.netbeans.lib.sql.NBCachedRowSet nBCachedRowSet1;
    private javax.swing.JLabel jLabel3111;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JLabel jLabel7111;
    private javax.swing.JLabel jLabel4111;
    private com.afrisoftech.lib.DatePicker datePicker1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jLabel61111;
    private javax.swing.JButton closebtn;
    private com.afrisoftech.lib.DatePicker datePicker111;
    private javax.swing.JPanel helppanel2;
    // End of variables declaration//GEN-END:variables
    
}
